name = "remix-testing"

zone_id = "cec98dba01cd801efa8c8872b6965ecd"
account_id = "f03ace5e69ab2a529ec5ec8a795e4507"
workers_dev = true

main = "./build/index.js"

compatibility_date = "2022-04-05"

[site]
bucket = "./public"

[build]
command = "yarn build"
